name: maet-pln

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python==3.12
  - pandas
  - numpy
  - torch
  - ipykernel
  - datasets # huggingface datasets (access to tl;dr dataset)
  - tqdm
  - python-dotenv
  - openai
  - transformers
  - trl
  - cohere
  - re
  - bitsandbytes
  - evaluate
  - huggingface_hub
  - bert_score
