name: maet-pln

channels:
  - anaconda
  - conda-forge
  - defaults
  - pip
  - pytorch

dependencies:
  - python==3.10.12
  - pandas
  - numpy
  - ipykernel
  - datasets # huggingface datasets (access to tl;dr dataset)
  - tqdm
  - python-dotenv
  - openai
  - transformers
  - huggingface_hub
  - pip
  - pytest
  - pytorch
  - chardet
  - nomkl
  # - bitsandbytes
  - pip:
    - torch
    - cchardet
    - trl
    - cohere
    - bitsandbytes
    - evaluate
    - pyarrow==12.0.0
    - git+https://github.com/lvwerra/trl.git
    - git+https://github.com/huggingface/accelerate.git
