name: maet-pln

channels:
  - anaconda
  - conda-forge
  - defaults
  - pip

dependencies:
  - python==3.12
  - pandas
  - numpy
  - ipykernel
  - datasets # huggingface datasets (access to tl;dr dataset)
  - tqdm
  - python-dotenv
  - openai
  - transformers
  - huggingface_hub
  - pip
  - pip:
    - torch
    - trl
    - cohere
    - bitsandbytes
